import "./unit/clock.test.mjs"
import "./unit/validation.test.mjs"
import "./unit/ordering.test.mjs"
import "./unit/ordering-advanced.test.mjs"
import "./unit/same-node-conflicts.test.mjs"
import "./unit/missing-dependencies.test.mjs"
import "./unit/invalid-data-survival.test.mjs"
import "./unit/stress-profiles.test.mjs"
import "./unit/publish-surface.test.mjs"
import "./unit/release-gate-current-core.test.mjs"
import "./fuzz/operational-outage-fuzz.test.mjs"
import "./fuzz/streaming-reconnect-pressure-fuzz.test.mjs"
import "./fuzz/streaming-watermark-pressure-fuzz.test.mjs"
import "./fuzz/streaming-reconnect-fuzz.test.mjs"
import "./streaming/late-arrival.test.mjs"
import "./streaming/release-gate-pressure.test.mjs"
import "./scenarios/replay-corruption.test.mjs"
import "./scenarios/multi-region-drift.test.mjs"
import "./scenarios/false-audit-timeline.test.mjs"
import "./scenarios/offline-sync-anomalies.test.mjs"
import "./scenarios/streaming-recovery-resync.test.mjs"
import "./scenarios/causal-inversion.test.mjs"
import "./scenarios/trace-and-partition-noncausal.test.mjs"

import { run } from "./helpers/harness.mjs"

await run()
